import "./globals.css";
import Footer from "@/components/Footer";
import AuthProvider from "@/context/AuthProvider";
import ConditionalHeader from "@/components/ConditionalHeader";

export const metadata = {
  title: "RK Dairy Farm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body>
        <AuthProvider>
          <ConditionalHeader />
          <section>{children}</section>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
